[2024-05-20T16:18:04.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-20T16:18:04.476+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-20T16:17:59.012444+00:00 [queued]>
[2024-05-20T16:18:04.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-20T16:17:59.012444+00:00 [queued]>
[2024-05-20T16:18:04.480+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2024-05-20T16:18:04.486+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): transform_load_weather_data> on 2024-05-20 16:17:59.012444+00:00
[2024-05-20T16:18:04.489+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=4154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-20T16:18:04.490+0000] {standard_task_runner.py:63} INFO - Started process 4156 to run task
[2024-05-20T16:18:04.490+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_dag', 'transform_load_weather_data', 'manual__2024-05-20T16:17:59.012444+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/weather_dag.py', '--cfg-path', '/tmp/tmphpp0uwjw']
[2024-05-20T16:18:04.492+0000] {standard_task_runner.py:91} INFO - Job 11: Subtask transform_load_weather_data
[2024-05-20T16:18:04.512+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_dag.transform_load_weather_data manual__2024-05-20T16:17:59.012444+00:00 [running]> on host 39024998a807
[2024-05-20T16:18:04.551+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_dag' AIRFLOW_CTX_TASK_ID='transform_load_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-20T16:17:59.012444+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-20T16:17:59.012444+00:00'
[2024-05-20T16:18:04.552+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-20T16:18:04.569+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-05-20T16:18:04.570+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-20T16:18:04.574+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_dag, task_id=transform_load_weather_data, run_id=manual__2024-05-20T16:17:59.012444+00:00, execution_date=20240520T161759, start_date=20240520T161804, end_date=20240520T161804
[2024-05-20T16:18:04.591+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-20T16:18:04.599+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-20T16:18:04.600+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
